// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTr3CFTzZlAL7TOfq653IVoodJqWq1jXI',
    appId: '1:674496746545:web:1987381ac397ee27abf110',
    messagingSenderId: '674496746545',
    projectId: 'my-app-flutter-908fb',
    authDomain: 'my-app-flutter-908fb.firebaseapp.com',
    storageBucket: 'my-app-flutter-908fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshZzUSfP0pGvMqCtJRf10ZpqOmiMXxe0',
    appId: '1:674496746545:android:1c37f556d5c315d4abf110',
    messagingSenderId: '674496746545',
    projectId: 'my-app-flutter-908fb',
    storageBucket: 'my-app-flutter-908fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAccydwr6mj98EpI2Nb4a7QcJ-_BdaVH_w',
    appId: '1:674496746545:ios:2b6715c7408eb8a5abf110',
    messagingSenderId: '674496746545',
    projectId: 'my-app-flutter-908fb',
    storageBucket: 'my-app-flutter-908fb.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
